version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:8.13.3
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-plugins:/usr/share/elasticsearch/plugins
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
  kibana:
    image: kibana:8.13.3
    container_name: kibana
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      I18N_LOCALE: zh-CN
    ports:
      - "5601:5601"


networks:
  default:
    external: true
    name: kong-net

volumes:
  es-data:
    external: true
  es-plugins:
    external: true